Device:
    enable: IOHUB_BOOL
    name:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True    
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: IOHUB_BOOL    
    device_timer:
        interval:
            IOHUB_FLOAT:
                min: 0.001
                max: 0.020
    event_buffer_length:
        IOHUB_INT:
            min: 1
            max: 2048    
    monitor_event_types:
        IOHUB_LIST: 
            valid_values: [ DeviceEvent,]
            min_length: 0
            max_length: 64
    device_number:
        IOHUB_INT:
            min: 0
            max: 32
    model_name:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
    manufacturer_name:
        IOHUB_STRING:
            min_length: 1
            max_length: 64
