eyetracker.hw.lc_technologies.eyegaze.EyeTracker:
    enable: IOHUB_BOOL
    name:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    device_timer:
        interval:
            IOHUB_FLOAT:
                min: 0.001
                max: 0.020
    event_buffer_length:
        IOHUB_INT:
            min: 1
            max: 1024
    display_camera_image: IOHUB_BOOL
    camera_image_screen_position:
        IOHUB_LIST:
            valid_values:  [UPPER_RIGHT, UPPER_LEFT] 
            min_length: 1
            max_length: 1            
    host_connection:
        type:        
            IOHUB_LIST:
                valid_values:  [LOCAL, SOCKET, SERIAL] 
                min_length: 1
                max_length: 1            
        # [SOCKET, 127.0.0.1] : eyegaze server ip address
        # [SERIAL, COM1] : COM address of serial port to use.
        parameter:
            IOHUB_STRING:
                min_length: 0
                max_length: 16            
    monitor_event_types:
        IOHUB_LIST:
            valid_values: [ MonocularEyeSampleEvent, BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]
            min_length: 0
            max_length: 8
    model_name:
        IOHUB_STRING:
            min_length: 1
            max_length: 16
    manufacturer_name: LC Technologies, Inc.
    device_number: 0
    model_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 16
    serial_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
    manufacture_date: IOHUB_DATE
    software_version:
        IOHUB_STRING:
            min_length: 1
            max_length: 8    
    hardware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
    firmware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
    # The below settings CAN NOT BE CHANGED!
    auto_report_events: False
