eyetracker.hw.tobii.EyeTracker:
    name: tracker
    enable: IOHUB_BOOL
    model_name:
        IOHUB_STRING:
            min_length: 0
            max_length: 64
    serial_number:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    license_file:
        IOHUB_STRING:
            min_length: 0
            max_length: 1024
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False
    event_buffer_length: 
        IOHUB_INT:
            min: 1
            max: 8192
    monitor_event_types: [BinocularEyeSampleEvent,]
    runtime_settings:
        sampling_rate:
            IOHUB_INT:
                min: 30
                max: 1200
        track_eyes: [BINOCULAR,]
    calibration:
        # The Tobii ioHub Common Eye Tracker Interface currently support 
        # a 3, 5 and 9 point calibration mode.
        # THREE_POINTS,FIVE_POINTS,NINE_POINTS
        type:
            IOHUB_LIST:
                valid_values: [THREE_POINTS, FIVE_POINTS, NINE_POINTS, THIRTEEN_POINTS]
                min_length: 1
                max_length: 1
        unit_type:
            IOHUB_LIST:
                valid_values: [norm, pix, cm, height, deg, degFlatPos, degFlat]
                min_length: 0
                max_length: 1
        color_type:
            IOHUB_LIST:
                valid_values: [rgb, dkl, lms, hsv, hex, named, rgb255]
                min_length: 0
                max_length: 1
        randomize: IOHUB_BOOL
        target_positions: []
        auto_pace: IOHUB_BOOL
        target_duration:
            IOHUB_FLOAT:
                min: 0.5
                max: 2.5
        target_delay:
            IOHUB_FLOAT:
                min: 0.5
                max: 2.5
        # pacing_speed is deprecated. Please use 'target_delay' instead.
        pacing_speed:
            IOHUB_FLOAT:
                min: 0.5
                max: 2.5
        screen_background_color: IOHUB_COLOR
        text_color: IOHUB_COLOR
        target_type:
            IOHUB_LIST:
                valid_values: [ CIRCLE_TARGET, CUSTOM ]
                min_length: 1
                max_length: 1
        target_attributes:
            custom:
                module_name:
                class_name:
                class_kwargs:
            outer_diameter:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            outer_stroke_width:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            outer_fill_color: IOHUB_COLOR
            outer_line_color: IOHUB_COLOR
            inner_diameter:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            inner_stroke_width:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            inner_fill_color: IOHUB_COLOR
            inner_line_color: IOHUB_COLOR
            animate:
                enable: IOHUB_BOOL
# movement_velocity is no longer supported, use target_delay instead.
#                movement_velocity:
#                    IOHUB_FLOAT:
#                        min: -1.0
#                        max: 1000.0
                expansion_ratio: # expands to 3 x the starting size
                    IOHUB_FLOAT:
                        min: 1.0
                        max: 100.0
# expansion_speed is no longer supported, use target_duration instead
#                expansion_speed:
#                    IOHUB_FLOAT:
#                        min: -1.0
#                        max: 100.0
                contract_only: IOHUB_BOOL
    device_number: 0
    manufacturer_name: Tobii Technology