# TODO G3 Specific Implementation
# These are the necessary default settings generic to all eye trackers.
eyetracker.hw.gazepoint.gp3.EyeTracker:
    name: 
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True
    enable: IOHUB_BOOL
    model_name: GP3
    serial_number:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    manufacturer_name: GazePoint
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False
    event_buffer_length: 
        IOHUB_INT:
            min: 1
            max: 2048
    monitor_event_types:           
        IOHUB_LIST:
            valid_values: [ MonocularEyeSampleEvent, BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]
            min_length: 0
            max_length: 8
    runtime_settings:
        sampling_rate: 60
        track_eyes: [BINOCULAR,]
    calibration:
        minimize_psychopy_win: IOHUB_BOOL
        type: [FIVE_POINTS,NINE_POINTS]
        randomize: False
        target_positions: []
        auto_pace: IOHUB_BOOL
        pacing_speed:
            IOHUB_FLOAT:
                min: 0.5
                max: 2.5
        screen_background_color: IOHUB_RGBA255_COLOR
        target_type: [CIRCLE_TARGET,]
        target_attributes:
            outer_diameter:
                IOHUB_INT:
                    min: 1
                    max: 1000
            outer_stroke_width:
                IOHUB_INT:
                    min: 1
                    max: 1000
            outer_fill_color: IOHUB_RGBA255_COLOR
            outer_line_color: IOHUB_RGBA255_COLOR
            inner_diameter:
                IOHUB_INT:
                    min: 1
                    max: 1000
            inner_stroke_width:
                IOHUB_INT:
                    min: 1
                    max: 1000
            inner_fill_color: IOHUB_RGBA255_COLOR
            inner_line_color: IOHUB_RGBA255_COLOR
            animate:
                enable: IOHUB_BOOL
                movement_velocity: # 300 pix / sec
                    IOHUB_FLOAT:
                        min: 1.0
                        max: 1000.0
                expansion_ratio: # expands to 3 x the starting size
                    IOHUB_FLOAT:
                        min: 1.0
                        max: 100.0
                expansion_speed: # exapands at 30.0 pix / sec
                    IOHUB_FLOAT:
                        min: 1.0
                        max: 100.0
                contract_only: IOHUB_BOOL

    device_number: 0
    manufacture_date: IOHUB_DATE
    model_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 16
    software_version:
        IOHUB_STRING:
            min_length: 1
            max_length: 8    
    hardware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
    firmware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8