name: conda-py2.7
channels:
- conda-forge
dependencies:
- python=2.7
- arabic_reshaper
- astunparse
- backports
- bzip2
- cffi
- codecov
- coveralls
- esprima-python
- gitpython
- ffmpeg
- freetype-py
- future
- gevent
- greenlet
- json_tricks
- libffi
- libflac
- lxml
- matplotlib
- moviepy
- msgpack-numpy
- msgpack-python
- numexpr
- numpy
- opencv
- openpyxl
- pandas
- pillow
- pip<19.0
- pixman
- prompt_toolkit
- psutil
- pycparser
- pygments
- pyopengl
- pyopenssl
- pyosf
- pyqt
- pyserial
- pysoundfile
- python-bidi
- pyyaml
- pyzmq
- requests
- scipy
- setuptools
- sip
- six
- pyglet>=1.3
- pytables
- python-gitlab
- urllib3
- wheel
- xlrd
- xz
- yaml
- lzo
- pytables
- pytest<4.1
- pytest-cov
- python-sounddevice
- wxpython!=4.0.2,!=4.0.3
- zlib
- pip:
  - pygame
  - pyparallel
