name: conda-py3.6
channels:
- conda-forge
dependencies:
- python=3.6
- arabic_reshaper
- astunparse
- backports
- bzip2
- cffi
- codecov
- coveralls
- esprima-python
- gitpython
- ffmpeg
- freetype-py
- future
- gevent
- greenlet
- hdf5
- json_tricks
- libflac
- lxml
- matplotlib
- moviepy
- msgpack-numpy
- msgpack-python
- numexpr
- numpy
- opencv
- openpyxl
- pandas
- pillow
- pip<19.0
- psutil
- pyopengl
- pyosf
- pyqt
- pyserial
- pysoundfile
- pytest<4.1
- pytest-cov
- python-bidi
- python-sounddevice
- pyyaml
- pyzmq
- requests
- scipy
- setuptools
- sip
- six
- pyglet>=1.3
- pytables
- python-gitlab
- urllib3
- wheel
- x264
- xlrd
- xz
- yaml
- lzo
- pytables
- wxpython!=4.0.2,!=4.0.3
- zlib
- pip:
  - pygame
  - pyparallel
