# experiment_config.yaml: settings related to the experiment being run when the run.py script is launched,
# any custom session variables you want displayed in a dialog for input at the start of the experiment

title: GC Cursor Demo
code: gc_cursor
version: '1.0'
description: User looks at an images while their eye position is plotted in real-time.
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
    user_variables:
        participant_age: Unknown
        #participant_gender: [ Select, Male, Female ]
        #glasses: [Select, Yes, No ]
        #contacts: [Select, Yes, No ]
        eye_color: Unknown
session_variable_order: [ name, code, comments, participant_age, eye_color ]
ioHub:
    enable: True
    config: iohub_config.yaml

  
