eyetracker.hw.mouse.EyeTracker:
    enable: True
    name: tracker
    monitor_event_types: [ MonocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]