name: conda-py3.8
channels:
- conda-forge
dependencies:
- python=3.8
- arabic_reshaper
- astunparse
- backports
- codecov
- coveralls
- distro
- esprima-python
- gitpython
- ffmpeg
- freetype-py
- future
- gevent
- greenlet
- imageio
- imageio-ffmpeg
- javascripthon
- json_tricks
- lxml
- matplotlib
- moviepy
- msgpack-numpy
- msgpack-python
- numpy
- opencv
- openpyxl
- pandas
- pillow
- pip!=19.0,!=19.0.1,!=19.0.2
- psutil
- pyglet>=1.3,<1.4
- pyglfw
- pyopengl
- pyosf
- pyqt
- pyserial
- pysoundfile
- pytables
- attrs<18.0
- pytest<4.1
- pytest-cov
- python-bidi
- python-gitlab
- python-sounddevice
- pyyaml
- pyzmq
- questplus
- requests
- scipy
- wheel
- wxpython
- xlrd
- pip
- pip:
  - pygame
  - pyparallel
