name: conda-py2.7
channels:
- conda-forge
dependencies:
- python=2.7
- arabic_reshaper
- astunparse
- backports
- codecov
- coveralls
- distro
- esprima-python
- gitpython
- ffmpeg
- freetype-py
- future
- gevent
- greenlet
- imageio<2.5
- json_tricks
- matplotlib
- moviepy
- msgpack-numpy
- msgpack-python
- numpy
- opencv
- openpyxl
- pandas
- pathlib
- pillow
- pip!=19.0,!=19.0.1,!=19.0.2
- psutil
- pyglet>=1.3,<1.4
- glfw!=3.3.1
- pyglfw
- pyopengl
- pyosf
- pyqt
- pyserial
- pysoundfile
- pytables
- attrs
- pytest
- python-bidi
- pytest-cov
- python-gitlab
- python-sounddevice
- pyyaml
- pyzmq
- requests
- scipy
- wheel
- wxpython!=4.0.2,!=4.0.3
- xlrd
- pip
- pip:
  - pygame
  - pyo
  - pyparallel
