eyetracker.hw.mouse.EyeTracker:
    name: tracker
    enable: IOHUB_BOOL
    device_timer:
        interval:
            IOHUB_FLOAT:
                min: 0.001
                max: 0.020
    model_name: MouseGaze
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False
    event_buffer_length:
        IOHUB_INT:
            min: 1
            max: 8192
    monitor_event_types:
        IOHUB_LIST:
            valid_values: [MonocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]
            min_length: 1
            max_length: 7
    controls:
        move:
            IOHUB_LIST:
                valid_values: [LEFT_BUTTON, MIDDLE_BUTTON, RIGHT_BUTTON, CONTINUOUS]
                min_length: 0
                max_length: 1
        blink:
            IOHUB_LIST:
                valid_values: [LEFT_BUTTON, MIDDLE_BUTTON, RIGHT_BUTTON]
                min_length: 0
                max_length: 3
        saccade_threshold:
            IOHUB_FLOAT:
                min: 0.1
                max: 2.0
    runtime_settings:
        sampling_rate:
            IOHUB_LIST:
                valid_values: [50, 100]
                min_length: 1
                max_length: 1
        track_eyes: RIGHT_EYE
    calibration:
        target_delay:
            IOHUB_FLOAT:
                min: 0.25
                max: 2.5
        target_duration:
            IOHUB_FLOAT:
                min: 0.25
                max: 2.5
        type:
            IOHUB_LIST:
                valid_values: [THREE_POINTS,FIVE_POINTS,NINE_POINTS, THIRTEEN_POINTS]
                min_length: 1
                max_length: 1
        unit_type:
            IOHUB_LIST:
                valid_values: [norm, pix, cm, height, deg, degFlatPos, degFlat]
                min_length: 0
                max_length: 1
        color_type:
            IOHUB_LIST:
                valid_values: [rgb, dkl, lms, hsv, hex, named, rgb255]
                min_length: 0
                max_length: 1
        auto_pace: IOHUB_BOOL
        randomize: IOHUB_BOOL
        screen_background_color: IOHUB_COLOR
        text_color: IOHUB_COLOR
        target_type:
            IOHUB_LIST:
                valid_values: [CIRCLE_TARGET, CUSTOM]
                min_length: 1
                max_length: 1
        target_attributes:
            custom:
                module_name:
                class_name:
                class_kwargs:
            outer_diameter:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            outer_stroke_width:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            outer_fill_color: IOHUB_COLOR
            outer_line_color: IOHUB_COLOR
            inner_diameter:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            inner_stroke_width:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            inner_fill_color: IOHUB_COLOR
            inner_line_color: IOHUB_COLOR
            animate:
                enable: IOHUB_BOOL
                expansion_ratio:
                    IOHUB_FLOAT:
                        min: 1.0
                        max: 100.0
                contract_only: IOHUB_BOOL
    device_number: 0
    manufacturer_name: MouseGaze
