eyetracker.hw.mouse.EyeTracker:
    name: tracker
    enable: IOHUB_BOOL
    device_timer:
        interval:
            IOHUB_FLOAT:
                min: 0.001
                max: 0.020
    model_name: MouseGaze
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False
    event_buffer_length:
        IOHUB_INT:
            min: 1
            max: 2048
    monitor_event_types:
        IOHUB_LIST:
            valid_values: [MonocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]
            min_length: 1
            max_length: 7
    runtime_settings:
        sampling_rate:
            IOHUB_LIST:
                valid_values: [50, 100]
                min_length: 1
                max_length: 1
        track_eyes: RIGHT_EYE
        saccade_threshold:
            IOHUB_INT:
                min: 0.1
                max: 2.0
    device_number: 0
    manufacturer_name: MouseGaze
    builder_hides: ['builder_hides', 'enable', 'name', 'device_number', 'device_timer', 'auto_report_events']
