!!python/unicode data_store: {!!python/unicode enable: true}
!!python/unicode monitor_devices:
- !!python/unicode Display:
    !!python/unicode default_eye_distance: {!!python/unicode surface_center: 500,
      !!python/unicode unit_type: !!python/unicode mm}
    !!python/unicode device_number: 0
    !!python/unicode name: !!python/unicode display
    !!python/unicode physical_dimensions: {!!python/unicode height: 340, !!python/unicode unit_type: !!python/unicode mm,
      !!python/unicode width: 590}
    !!python/unicode psychopy_monitor_name: !!python/unicode default
    !!python/unicode reporting_unit_type: !!python/unicode pix
- !!python/unicode Keyboard: {!!python/unicode name: !!python/unicode keyboard}
- !!python/unicode Mouse: {!!python/unicode name: !!python/unicode mouse}
- !!python/unicode Experiment: {!!python/unicode name: !!python/unicode experimentRuntime}
- !!python/unicode eyetracker.hw.sr_research.eyelink.EyeTracker:
    !!python/unicode calibration:
      !!python/unicode auto_pace: true
      !!python/unicode pacing_speed: 1.5
      !!python/unicode screen_background_color: [128, 128, 128]
      !!python/unicode target_attributes:
        !!python/unicode inner_color: [0, 0, 0]
        !!python/unicode inner_diameter: 6
        !!python/unicode outer_color: [255, 255, 255]
        !!python/unicode outer_diameter: 33
      !!python/unicode target_type: !!python/unicode CIRCLE_TARGET
      !!python/unicode type: !!python/unicode NINE_POINTS
    !!python/unicode default_native_data_file_name: !!python/unicode et_data
    !!python/unicode device_timer: {!!python/unicode interval: 0.001}
    !!python/unicode enable: true
    !!python/unicode enable_interface_without_connection: false
    !!python/unicode event_buffer_length: 1024
    !!python/unicode model_name: !!python/unicode EYELINK 1000 DESKTOP
    !!python/unicode monitor_event_types: [!!python/unicode MonocularEyeSampleEvent,
      !!python/unicode BinocularEyeSampleEvent, !!python/unicode FixationStartEvent,
      !!python/unicode FixationEndEvent, !!python/unicode SaccadeStartEvent, !!python/unicode SaccadeEndEvent,
      !!python/unicode BlinkStartEvent, !!python/unicode BlinkEndEvent]
    !!python/unicode name: !!python/unicode tracker
    !!python/unicode network_settings: !!python/unicode 100.1.1.1
    !!python/unicode runtime_settings:
      !!python/unicode sample_filtering: {!!python/unicode FILTER_FILE: !!python/unicode FILTER_LEVEL_2,
        !!python/unicode FILTER_ONLINE: !!python/unicode FILTER_OFF}
      !!python/unicode sampling_rate: 500
      !!python/unicode track_eyes: !!python/unicode BINOCULAR
      !!python/unicode vog_settings: {!!python/unicode pupil_center_algorithm: !!python/unicode CENTROID_FIT,
        !!python/unicode pupil_measure_types: !!python/unicode PUPIL_AREA, !!python/unicode tracking_mode: !!python/unicode PUPIL_CR_TRACKING}
    !!python/unicode save_events: true
    !!python/unicode simulation_mode: false
    !!python/unicode stream_events: true
