!!python/unicode data_store: {!!python/unicode enable: true}
!!python/unicode monitor_devices:
- !!python/unicode Display:
    !!python/unicode default_eye_distance: {!!python/unicode surface_center: 500,
      !!python/unicode unit_type: !!python/unicode mm}
    !!python/unicode device_number: 0
    !!python/unicode name: !!python/unicode display
    !!python/unicode physical_dimensions: {!!python/unicode height: 340, !!python/unicode unit_type: !!python/unicode mm,
      !!python/unicode width: 590}
    !!python/unicode psychopy_monitor_name: !!python/unicode default
    !!python/unicode reporting_unit_type: !!python/unicode pix
- !!python/unicode Keyboard: {!!python/unicode name: !!python/unicode keyboard}
- !!python/unicode Mouse: {!!python/unicode name: !!python/unicode mouse}
- !!python/unicode Experiment: {!!python/unicode name: !!python/unicode experimentRuntime}
- !!python/unicode eyetrackerhw.gazepoint.gp3.EyeTracker:
    !!python/unicode device_timer: {!!python/unicode interval: 0.002}
    !!python/unicode enable: true
    !!python/unicode event_buffer_length: 256
    !!python/unicode monitor_event_types: [!!python/unicode BinocularEyeSampleEvent]
    !!python/unicode name: !!python/unicode tracker
