eyetracker.hw.sr_research.eyelink.EyeTracker:
    name: tracker
    enable: IOHUB_BOOL
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False 
    device_timer:
        interval:
            IOHUB_FLOAT:
                min: 0.001
                max: 0.020
    event_buffer_length: 
        IOHUB_INT:
            min: 1
            max: 8192
    monitor_event_types:           
        IOHUB_LIST:
            valid_values: [ MonocularEyeSampleEvent, BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]  
            min_length: 1
            max_length: 8            
    calibration:
        type:
            IOHUB_LIST:
                valid_values: [THREE_POINTS, FIVE_POINTS, NINE_POINTS, THIRTEEN_POINTS]
                min_length: 1
                max_length: 1
        unit_type:
            IOHUB_LIST:
                valid_values: [norm, pix, cm, height, deg, degFlatPos, degFlat]
                min_length: 0
                max_length: 1
        color_type:
            IOHUB_LIST:
                valid_values: [rgb, dkl, lms, hsv, hex, named, rgb255]
                min_length: 0
                max_length: 1
        auto_pace: IOHUB_BOOL
        target_duration:
            IOHUB_FLOAT:
                min: 0.5
                max: 2.5
        target_delay:
            IOHUB_FLOAT:
                min: 0.5
                max: 2.5
        # pacing_speed is deprecated. Please use 'target_delay' instead.
        pacing_speed:
            IOHUB_FLOAT:
                min: 0.5
                max: 2.5
        screen_background_color: IOHUB_COLOR
        text_color: IOHUB_COLOR
        target_type:
            IOHUB_LIST:
                valid_values: [CIRCLE_TARGET, CUSTOM]
                min_length: 1
                max_length: 1
        target_attributes:
            custom:
                module_name:
                class_name:
                class_kwargs:
            outer_diameter:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 250.0
            outer_stroke_width:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            outer_fill_color: IOHUB_COLOR
            outer_line_color: IOHUB_COLOR
            inner_diameter:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 250.0
            inner_stroke_width:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            inner_fill_color: IOHUB_COLOR
            inner_line_color: IOHUB_COLOR
            # Deprecated. Use 'outer_fill_color' and 'outer_line_color'
            outer_color: IOHUB_COLOR
            # Deprecated. Use 'outer_fill_color' and 'outer_line_color'
            inner_color: IOHUB_COLOR
    simulation_mode: IOHUB_BOOL
    enable_interface_without_connection: IOHUB_BOOL
    network_settings: IOHUB_IP_ADDRESS_V4
    default_native_data_file_name: 
        IOHUB_STRING:
            min_length: 0
            max_length: 7
    runtime_settings:
        sampling_rate:
            IOHUB_LIST:
                valid_values: [250,500,1000,2000]
                min_length: 1
                max_length: 1
        track_eyes:
            IOHUB_LIST:
                valid_values: [LEFT_EYE, RIGHT_EYE, BOTH]
                min_length: 1
                max_length: 1
        sample_filtering:
            FILTER_ALL: 
                IOHUB_LIST:
                    valid_values:  [FILTER_LEVEL_OFF, FILTER_LEVEL_1, FILTER_LEVEL_2] 
                    min_length: 1
                    max_length: 1            
            FILTER_FILE: 
                IOHUB_LIST:
                    valid_values:  [FILTER_LEVEL_OFF, FILTER_LEVEL_1, FILTER_LEVEL_2] 
                    min_length: 1
                    max_length: 1            
            FILTER_ONLINE: 
                IOHUB_LIST:
                    valid_values:  [FILTER_LEVEL_OFF, FILTER_LEVEL_1, FILTER_LEVEL_2] 
                    min_length: 1
                    max_length: 1            
        vog_settings:
            pupil_measure_types:
                IOHUB_LIST:
                    valid_values:  [PUPIL_AREA,PUPIL_DIAMETER] 
                    min_length: 1
                    max_length: 1            
            tracking_mode:
                IOHUB_LIST:
                    valid_values:  [PUPIL_CR_TRACKING, PUPIL_ONLY_TRACKING] 
                    min_length: 1
                    max_length: 1            
            pupil_center_algorithm:
                IOHUB_LIST:
                    valid_values:  [ELLIPSE_FIT, CENTROID_FIT] 
                    min_length: 1
                    max_length: 1            
    model_name: 
        IOHUB_LIST:
            valid_values: [EYELINK 1000 DESKTOP, EYELINK 1000 TOWER, EYELINK 1000 REMOTE, EYELINK 1000 LONG RANGE]
            min_length: 1
            max_length: 1            
    device_number: 0
    # manufacturer_name:    Used by Builder as the displayed name in the eye tracker selection dropdown.
    #
    manufacturer_name: SR Research Ltd
